---
version: '2'

services:
  deezer-downloader:
    build: .
    environment:
      - DEEZER_COOKIE_ARL=changeme
      - DEEZER_FLAC_QUALITY=false
    volumes:
      - ./downloads:/mnt/deezer-downloader
    ports:
      - "5000:5000"
